# Module 1 - Introducing Libraries: NumPy

### Introduction

#### _Our goals today are to be able to_: <br/>

- Identify and import Python libraries
- Identify differences between NumPy and base Python in usage and operation

#### _Big questions for this lesson_: <br/>
- What is a package, what do packages do, and why might we want to use them?
- When do we want to use NumPy?

### Activation:

![excel](images/excelpic.jpg)

Most people have used Microsoft Excel or Google sheets. But what are the limitations of excel?

- [Take a minute to read this article](https://www.bbc.com/news/magazine-22223190)
- make a list of problems excel presents

How is using python different?

### 1. Importing Python Libraries


Previously, we wrote a function to calculate the mean of an list. That was **tedious**.

Thankfully, other people have wrote and optimized functions and wrapped them into **libraries** we can then call and use in our analysis.

![numpy](https://raw.githubusercontent.com/donnemartin/data-science-ipython-notebooks/master/images/numpy.png)

[NumPy](https://www.numpy.org/) is the fundamental package for scientific computing with Python. 


To import a package type `import` followed by the name of the library as shown below.

In [ ]:
import numpy as np
import numpy

x = numpy.array([1, 2, 3])
print(x)

# Many packages have a canonical way to import them

y = np.array([4, 5, 6])
print(y)

Because of numpy we can now get the **mean** and other quick math of lists and arrays.

In [ ]:
example = [4, 3, 25, 40, 62, 20]
print(np.mean(example))

Now let's import some other packages. We will cover in more detail some fun options for numpy later.

In [ ]:
import scipy
import pandas as pd
import matplotlib as mpl

In [ ]:
# sometimes we will want to import a specific module from a library
import matplotlib.pyplot as plt
from matplotlib.pyplot import plot

# What happens when we uncomment the next line?
# %matplotlib inline

plt.plot(x, y)

In [ ]:
# OR we can also import it this way
from matplotlib import pyplot as plt
plt.plot(x, y)

Try importing the seaborn library as ['sns'](https://en.wikipedia.org/wiki/Sam_Seaborn) which is the convention.

In [ ]:
# your code here


What happens if we mess with naming conventions? For example, import one of our previous libraries as `print`.


PLEASE NOTE THAT WE WILL HAVE TO RESET THE KERNEL AFTER RUNNING THIS. Comment out your code after running it.


In [ ]:
# your code here


In [ ]:
# What about when we run the following command?
max = [1, 2, 3]

# We've ruined _everything_. Restart your kernel!

#### Helpful links: library documenation

Libraries have associated documentation to explain how to use the different tools included in a library.

- [NumPy](https://docs.scipy.org/doc/numpy/)
- [SciPy](https://docs.scipy.org/doc/scipy/reference/)
- [Pandas](http://pandas.pydata.org/pandas-docs/stable/)
- [Matplotlib](https://matplotlib.org/contents.html)

### 2. NumPy versus base Python

Now that we know libraries exist, why do we want to use them? Let us examine a comparison between base Python and Numpy.

Python has lists and normal python can do basic math. NumPy, however, has the helpful objects called arrays.

Numpy has a few advantages over base Python which we will look at.

In [ ]:
import numpy as np

In [ ]:
names_list = ['Bob', 'John', 'Sally']
names_array = np.array(['Bob', 'John', 'Sally'])
print(names_list)
print(names_array)
names_array

In [ ]:
# Make a list and an array of three numbers
# your code here

In [ ]:
# divide your array by 2


In [ ]:
# divide your list by 2


Numpy arrays support the `/` operator (which calls the `__div__()` method) while python lists do not. There are other things that make it useful to utilize numpy over base python for evaluating data.

In [ ]:
# shape tells us the size of the array

numbers_array.shape

In [ ]:
numbers_array

In [ ]:
# Selection and assignment work as you might expect
numbers_array[1]

Take 5 minutes and explore each of the following functions.  What does each one do?  What is the syntax of each?
- `np.zeros()`
- `np.ones()`
- `np.full()`
- `np.eye()`
- `np.random.random()`

### Slicing in NumPy

In [ ]:
# We remember slicing from lists
numbers_list = list(range(10))
numbers_list[3:7]

In [ ]:
# Slicing in NumPy Arrays is very similar!
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

In [ ]:
# first 2 rows, columns 1 & 2 (remember 0-index!)
b = a[:2, 1:3]
b

### Datatypes in NumPy

In [ ]:
a.dtype

In [ ]:
names_array.dtype

In [ ]:
a.astype(np.float64).dtype

### More Array Math

In [ ]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; both produce the same array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(x ** .5)
print(np.sqrt(x))

Below, you will find a piece of code we will use to compare the speed of operations on a list and operations on an array. In this speed test, we will use the library [time](https://docs.python.org/3/library/time.html).

In [ ]:
import time
import numpy as np

size_of_vec = 1000


def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X))]
    return time.time() - t1


def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1


t1 = pure_python_version()
t2 = numpy_version()
print("python: " + str(t1), "numpy: " + str(t2))
print("Numpy is in this example " + str(t1/t2) + " times faster!")

In pairs, run the speed test with a different number, and share your results with the class.

## Enter: Pandas

<img src="https://cdn-images-1.medium.com/max/1600/1*9IU5fBzJisilYjRAi-f55Q.png" width=600>  




- The data manipulation capabilities of Pandas are built on top of the numpy library.
- Pandas dataframe object represents a spreadsheet with cell values, column names, and row index labels.

### 1. Importing and reading data with Pandas!

#### Let's use pandas to read some csv files so we can interact with them.



In [ ]:
# First, let's check which directory we are in so the files we expect to see are there.
!pwd
!ls -la

In [ ]:
import pandas as pd

example_csv = pd.read_csv('data/example1.csv')

There is also `read_excel`, `read_html`, and many other pandas `read_` functions.  
http://pandas.pydata.org/pandas-docs/stable/user_guide/io.html

In [ ]:
example_csv.describe()

Try loading in the example file in the `data` directory called `made_up_jobs.csv` using pandas.

In [ ]:
# read in your csv here!
muj = pd.read_csv('data/made_up_jobs.csv')

# remember that it's nice to be able to look at your data, so let's do that here, too.
muj.head()

### 2. Utilizing and identifying Pandas objects

- What is a DataFrame object and what is a Series object? 
- How are they different from Python lists?

These are questions we will cover in this section. To start, let's start with this list of fruits.

In [ ]:
fruits = ['Apple', 'Orange', 'Watermelon', 'Lemon', 'Mango']

print(fruits)

Using our list of fruits, we can create a pandas object called a 'series' which is much like an array or a vector.

In [ ]:
fruits_series = pd.Series(fruits)

print(fruits_series)
type(fruits_series)

One difference between python **list objects** and pandas **series objects** is the fact that you can define the index manually for a **series objects**.

In [ ]:
ind = ['a', 'b', 'c', 'd', 'e']

fruits_series = pd.Series(fruits, index=ind)

print(fruits_series)

With a partner, create your own custom series from a list of lists.

In [ ]:
list_of_lists = [['cat'], ['dog'], ['horse'], ['cow'], ['macaw']]

# create custom indices for your series
ind = ['a', 'b', 'c', 'd', 'e']

elements=[x[0].lower() for x in list_of_lists]

# create the series using your list objects
# You can use either a for loop or also pd.Series
list_of_lists_series = pd.Series(elements, index=ind)

# print your series
print(list_of_lists_series)
type(list_of_lists_series)

We can do a simliar thing with Python dictionaries. This time, however, we will create a DataFrame object from a python dictionary.

In [ ]:
# Dictionary with list object in values
student_dict = {
    'name': ['Samantha', 'Alex', 'Dante'],
    'age': ['35', '17', '26'],
    'city': ['Houston', 'Seattle', 'New york']
}

students_df = pd.DataFrame(student_dict)

students_df.head()

In [ ]:
#to find data types of columns
students_df.dtypes

Let's change the data type of ages to int.

In [ ]:
# We can also change a columns type but the change has to make sense.
students_df.age = students_df.age.values

#Uncomment line below and observe what happens when trying to convert student's name to int or float
#students_df.name = students_df.name.astype(int)

#How about what happens converting numeric to string
students_df.age = students_df.age.astype(str)

students_df.dtypes

We can also use a custom index for these items. For example, we might want them to be the individual student ID numbers.

In [ ]:
school_ids = ['1111', '1145', '0096']

# Notice here we use pd.DataFrame not pd.Series as we did for a pandas series.
students_df = pd.DataFrame(student_dict, index=school_ids)

students_df.head()

Using Pandas, we can also rename column names.

In [ ]:
students_df.columns = ['NAME', 'AGE', 'HOME']
students_df.head()

Or, we can also change the column names using the rename function.

In [ ]:
students_df.rename(columns={"AGE": "YEARS"})

In [ ]:
# Notice what happens when we print students_df

students_df

In [ ]:
# If you want the file to save over itself, use the option `inplace = True`.
students_df.rename(columns={'AGE': 'YEARS'}, inplace=True)
students_df.head()

Similarly, there is a tool to remove rows and columns from your DataFrame

In [ ]:
students_df.drop(columns=['YEARS', 'HOME'])

In [ ]:
#Notice again what happens if we print students_df 
students_df

In [ ]:
students_df.drop(columns=['YEARS', 'HOME'], inplace=True)
students_df

If you want the file to save over itself, use the option `inplace = True`.

Every function has options. Let's read more about `drop` [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html)

### 3. Filtering Data Using Pandas
There are several ways to grab particular data from a DataFrame. 
- Python lists allow for selection of data only through integer location. 
- You can use a single integer or slice notation to make the selection but NOT a list of integers.
- Dictionaries only allow selection with a single label. Slices and lists of labels are not allowed.

In [ ]:
l = [1, 2, 3, 4, 5]
l[[0, 5]]

### DataFrames can be indexed by column name (label) or row name (index) or by position.   
#### The `.loc` method is used for indexing by name.  
#### While `.iloc` is used for indexing by number.

In [ ]:
student_dict = {
    'name': ['Samantha', 'Alex', 'Dante'],
    'age': ['35', '17', '26'],
    'city': ['Houston', 'Seattle', 'New york']
}

students_df = pd.DataFrame(student_dict)

In [ ]:
students_df.loc[:, 'name']

### Let's take a look at `.iloc`
#### `.iloc` takes slices based on index position.
#### `.iloc` stands for integer location so that should help with remember what it does
#### `.iloc`[row , column]

In [ ]:
# returns the first row
students_df.iloc[0]

In [ ]:
# returns the first column
students_df.iloc[:, 0]

In [ ]:
# returns first two rows notice that ILOC performs regular python slicing.
students_df.iloc[0:2]

In [ ]:
# returns the first two columns
students_df.iloc[:, 0:2]

In [ ]:
# returns first row and columns 1 and 2
students_df.iloc[0:1, 0:2]

### How would we use `.iloc` to return the last item in the last row?


In [ ]:
# return the last item in the last row using iloc

### How would we use `.iloc` to return the last item in the last column?


In [ ]:
# return the last item in the last column using iloc

### What if we only want certain columns or rows?

In [ ]:
# Don't do students_df.iloc[0, 2]
students_df.iloc[[0, 2]]

In [ ]:
students_df.iloc[[0, 2], [0, 2]]

### Let's take a look at `.loc`
#### Label based method. 
#### Names or labels of the index is used when taking slices.
#### Also supports boolean subsetting.

In [ ]:
# We will use loc to return rows and columns based on labels. Let's look at the students_df DataFrame again.
students_df

In [ ]:
# returns the student information associated with index 0
students_df.loc[0]

In [ ]:
# returns the student information for row index 0 to 2 inclusive.
# note iloc would return normal python slicing not including 2 as demonstrated above.
students_df.loc[0:2]

In [ ]:
# returns the column labeled 'age'
students_df.loc[:, 'age']

In [ ]:
# returns the column labeled 'age' and index values 1 to 2.
# gives us the values of the rows with index from 1 to 2 (inclusive)
# and columns labeled age"
students_df.loc[1:2, 'age']

In [ ]:
# returns the column labeled 'age' and index values 1 to 2.
# gives us the values of the rows with index from 1 to 2 (inclusive)
# and columns labeled age to city (inclusive)"
students_df.loc[1:2, 'age':'city']

In [ ]:
# What should we get?
students_df.loc[1:2, ['name', 'city']]

In [ ]:
# How about?
students_df.loc[[0, 2], ['name', 'city']]

In [ ]:
# if index rearranged
school_ids = ['5', '11', '3']
students_df = pd.DataFrame(student_dict, index=school_ids)

In [ ]:
students_df

In [ ]:
# What should we get now?
students_df.loc[[0, 2], ['name', 'city']]

In [ ]:
# What should we get now?
students_df.loc[['5', '11'], ['name', 'city']]

In [ ]:
students_df.set_index("name", inplace=True)
students_df

In [ ]:
students_df.loc[['Samantha']]

In [ ]:
# Subsetting nonconsecutive rows
students_df.loc[['Samantha', 'Dante']]

In [ ]:
# Samantha to the end
students_df.loc['Samantha':]

In [ ]:
# return the first and last rows using one loc command

### Boolean Subsetting

In [ ]:
student_dict = {
    'name': ['Samantha', 'Alex', 'Dante', 'Samantha'],
    'age': ['35', '17', '26', '21'],
    'city': ['Houston', 'Seattle', 'New york', 'Atlanta'],
    'state': ['Texas', 'Washington', 'New York', 'Georgia']
}

students_df = pd.DataFrame(student_dict)

In [ ]:
# The statement data[‘name’] == ‘Samantha’] produces a Pandas Series with a True/False value for every row
# in the ‘data’ DataFrame, where there are “True” values for the rows where the name is “Samantha”.
# These type of boolean arrays can be passed directly to the .loc indexer.
students_df.loc[students_df['name'] == 'Samantha']

In [ ]:
# What about if we only want the city and state of the selected students with the name Samantha?
students_df.loc[students_df['name'] == 'Samantha', ['city', 'state']]

In [ ]:
# What amount if we want to select a student of a specific age?
students_df.loc[students_df['age'] == '21']

In [ ]:
# What amount if we want to select a student of a specific age?
students_df.loc[(students_df['age'] == '21') &
                (students_df['city'] == 'Atlanta')]

In [ ]:
# What should be returned?
students_df.loc[(students_df['age'] == '35') &
                (students_df['city'] == 'Atlanta')]

### Lesson Recap
Pandas combines the power of python lists (selection via integer location) and dictionaries (selection by label)

`.iloc` is primarily integer position based (from 0 to length-1 of the axis), but may also be used with a boolean array.

`.iloc` will raise IndexError if a requested indexer is out-of-bounds, except slice indexers which allow out-of-bounds indexing (this conforms with python/numpy slice semantics).

`.loc` is primarily label based, but may also be used with a boolean array.

#### Warning Note that contrary to usual python slices, both the start and the stop are included.

`.loc` will raise a keyError when any items are not found.

### Pandas
- The data structures in Pandas are implemented using series and dataframe classes.  
- A series is a one-dimensional indexed array of some fixed data type.  
- While a dataframe is a two-dimensional data structure like a table where each column contains data of the same type.  
- DataFrames are great for representing real data: rows correspond to instances (examples, observations, etc.), and columns correspond to features of these instances.
